[theme]
base = "light"
primaryColor = "#d63384"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f8f8"
textColor = "#000000"
font = "sans serif"

[server]
runOnSave = true
maxUploadSize = 10
enableStaticServing = true

[browser]
gatherUsageStats = false